//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madelman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialsSpec = new HashSet<MaterialsSpec>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public string Title { get; set; }
        public Nullable<int> UnitsId { get; set; }
        public Nullable<decimal> Length_m_ { get; set; }
        public Nullable<int> Count { get; set; }
        public int MaterialTypeId { get; set; }
        public Nullable<decimal> Coast { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string GOST { get; set; }
        public string Specification { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual MaterialsType MaterialsType { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsSpec> MaterialsSpec { get; set; }
    }
}
