//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madelman
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationSpec
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Operation { get; set; }
        public int Number { get; set; }
        public int EquipmentTypeId { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
